name: Test no optional

on:
  push:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --no-optional=false

      - name: Test
        run: |
          pnpm --version
          ls -al ./node_modules/.pnpm | grep "@img"
